spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3307/mybatis-plus?useUnicode=yes&characterEncoding=UTF-8&useSSL=false